ansible_ssh_private_key_file: ~/.ssh/ansible_rsa
ansible_ssh_public_key_file: "{{lookup('file', '~/.ssh/ansible_rsa.pub') }}"
resource_group: mydockerswarm
location: northeurope
sku_tier: Standard
admin_username: azureuser
worker_name: "{{ resource_group }}-worker"
manager_name: "{{ resource_group }}-manager"
image_offer: CentOS
image_publisher: OpenLogic
image_sku: "8_3-gen2"
image_version: "8.3.2021020401"
sg_allow_address: Internet
number_of_workers: 1
list_of_managers:
  - 10.1.0.10
