---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ resource_group }}"
    address_prefixes: "{{ vnet_cidr }}"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ resource_group }}"
    address_prefix: "{{ subnet_cidr }}"
    virtual_network: "{{ resource_group }}"

- name: Create availability set
  azure_rm_availabilityset:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    resource_group: "{{ resource_group }}"
    platform_update_domain_count: 5
    platform_fault_domain_count: 2
    sku: Aligned

- name: Create network security group that allows SSH and services
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ resource_group }}"
    rules:
      - name: SSH
        protocol: Tcp
        source_address_prefix: "{{ sg_allow_address }}"
        destination_address_prefix: VirtualNetwork
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: Docker
        protocol: Tcp
        source_address_prefix: "{{ sg_allow_address }}"
        destination_address_prefix: VirtualNetwork
        destination_port_range: 2376
        access: Allow
        priority: 1002
        direction: Inbound
      - name: Port_80
        protocol: Tcp
        source_address_prefix: "{{ sg_allow_address }}"
        destination_address_prefix: VirtualNetwork
        destination_port_range: "{{ application_port }}"
        access: Allow
        priority: 1003
        direction: Inbound

- name: Create LB public ip address
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    name: "{{ resource_group }}-lb"
    sku: "{{ sku_tier }}"

- name: Create load balancer
  azure_rm_loadbalancer:
    resource_group: "{{ resource_group }}"
    name: "{{ resource_group }}-lb"
    location: "{{ location }}"
    sku: "{{ sku_tier }}"
    frontend_ip_configurations:
      - name: "{{ resource_group }}-frontconfig"
        public_ip_address: "{{ resource_group }}-lb"
    backend_address_pools:
      - name: "{{ resource_group }}-managers"
      - name: "{{ resource_group }}-allnodes"
    probes:
      - name: "{{ resource_group }}-prob0"
        port: 2376
        interval: 10
        fail_count: 3
      - name: "{{ resource_group }}-prob1"
        port: "{{ application_port }}"
        interval: 10
        fail_count: 3
    load_balancing_rules:
      - name: "{{ resource_group }}-rule0"
        frontend_ip_configuration: "{{ resource_group }}-frontconfig"
        backend_address_pool: "{{ resource_group }}-managers"
        frontend_port: 2376
        backend_port: 2376
        load_distribution: Default
        probe: "{{ resource_group }}-prob0"
      - name: "{{ resource_group }}-rule1"
        frontend_ip_configuration: "{{ resource_group }}-frontconfig"
        backend_address_pool: "{{ resource_group }}-allnodes"
        frontend_port: "{{ application_port }}"
        backend_port: "{{ application_port }}"
        load_distribution: Default
        probe: "{{ resource_group }}-prob1"
