---
- import_tasks: tasks/swarm-extra.yml

- name: Add worker nodes
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ ansible_eth0.ipv4.address }}"
    join_token: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: "{{ swarm_info | community.general.json_query('nodes[*].ManagerStatus.Addr') }}"
